---
- name: Install dependencies of Linuxbrew
  become: true
  apt: 
    name: "{{ packages }}" 
    state: present
  vars:
    packages:
      - curl
      - file
      - git
      - build-essential
  
- name: Install Linuxbrew
  become: false
  shell: "sh -c \"$(curl -fsSL https://raw.githubusercontent.com/Linuxbrew/install/master/install.sh)\""
  register: linuxbrew

- name: Set /etc/profile.d/linuxbrew.sh
  become: true
  copy: src=linuxbrew.sh dest=/etc/profile.d/linuxbrew.sh

- name: Install brew packages
  homebrew: 
    name: "{{ packages }}"
    state: present
  vars:
    packages:
      - tmux
      - ghq
      - go
      - fzf
      - shellcheck
      - shfmt
      - jq
      - translate-shell
  environment:
    PATH: "/home/linuxbrew/.linuxbrew/bin:{{ ansible_env.PATH }}"

- name: Set ghq root
  git_config: name=ghq.root scope=global value="~/src"

