---
- name: install package
  become: true
  apt:
    name: "{{ packages }}"
    state: present
  vars:
    packages:
      - zsh

- debug: var={{ ansible_ssh_user }}

- name: change default shell
  become: true
  command: chsh -s /bin/zsh {{ ansible_ssh_user }}
