---
- name: Ensure .vim/autoload dir exists
  file: path=~/.vim/autoload state=directory
- name: Install vim-plug
  become: false
  get_url: url="https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim" dest=~/.vim/autoload/plug.vim
  register: vim-plug

